# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureFileCopy@4
  inputs:
    SourcePath: 'CreateWebApp/azuredeploy.json'
    azureSubscription: 'devops250122'
    Destination: 'AzureBlob'
    storage: 'storacc1717'
    ContainerName: 'cont1717'
  name: AzureFileCopy

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'devops250122'
    subscriptionId: '6ee4be50-e10e-498b-b751-6dcdb3ba8a8d'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'testcourse'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: '$(AzureFileCopy.StorageContainerUri)CreateWebApp/azuredeploy.json?sp=r&st=2022-02-04T11:43:48Z&se=2022-02-04T19:43:48Z&spr=https&sv=2020-08-04&sr=c&sig=9hze02uDhTNiHjLIuDKAUuQGPhJnS4Y%2Bajw4HI%2Fbatw%3D'
    deploymentMode: 'Incremental'
    deploymentName: 'deploy1'